INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

HEADERS += \
    $$PWD/power_oper.h \
    $$PWD/takeout_cook.h \
    $$PWD/take_cashier.h \
    $$PWD/sqlquerymodel_linenum1.h \
    $$PWD/take_weight.h \
    $$PWD/bank_card.h \
    $$PWD/free_view.h \
    $$PWD/other_pay_view.h \
    $$PWD/waimai_pay.h \
    $$PWD/modify_password.h \
    $$PWD/lock_screen.h \
    $$PWD/business_documents_query.h \
    $$PWD/fast_qudan.h \
    $$PWD/bianma_cook.h \
    $$PWD/back_anti_checkout.h \
    $$PWD/w_scr_dish.h \
    $$PWD/w_scr_dish_data_collection.h \
    $$PWD/w_scr_dish_switch_detail.h \
    $$PWD/w_scr_balance_service.h \
    $$PWD/table_lock.h \
    $$PWD/linshi_cook.h \
    $$PWD/w_scr_dish_restaurant_dialog.h \
    $$PWD/w_scr_dish_cuicai_choose.h \
    $$PWD/w_scr_dish_cuicaipiece_choose.h \
    $$PWD/fast_pay_detail_dialog.h \
    $$PWD/w_scr_dish_m_hang_dialog.h \
    $$PWD/w_scr_dish_m_hang_pay_dialog.h \
    $$PWD/w_scr_dish_preorder_dialog.h \
    $$PWD/w_scr_dish_barscale.h \
    $$PWD/w_scr_dish_dish_change.h \
    $$PWD/w_scr_dish_restaurant_preorder.h \
    $$PWD/w_scr_dish_select_operid.h \
    $$PWD/system_setting_mobile_max_connect.h \
    $$PWD/w_scr_dish_restaurant_div_pop.h \
    $$PWD/w_scr_dish_restaurant_table_copy.h \
    $$PWD/w_scr_dish_restaurant_table_cmb.h \
    $$PWD/w_scr_dish_restaurant_table_transfer.h \
    $$PWD/w_scr_dish_num_cook_dialog.h \
    $$PWD/w_scr_dish_dish_quit.h \
    $$PWD/w_scr_dish_member.h \
    $$PWD/w_scr_dish_restaurant_table_dish_transfer.h \
    $$PWD/w_scr_dish_restaurant_table_select.h \
    $$PWD/w_scr_dish_pay_set.h \
    $$PWD/table_management_graphicsview.h \
    $$PWD/table_management_pad.h \
    $$PWD/table_management_desk.h \
    $$PWD/w_scr_dish_restaurant_paysomedish.h \
    $$PWD/w_scr_dish_restaurant_parameter.h \
    $$PWD/business_data_upload_isoft.h \
    $$PWD/w_scr_dish_group_dialog.h \
    $$PWD/w_scr_dish_pay_module_select.h \
    $$PWD/w_scr_dish_cook.h \
    $$PWD/w_scr_dish_guqing_report.h \
    $$PWD/w_scr_dish_language_switch_set.h \
    $$PWD/w_scr_dish_pay_select_language.h \
    $$PWD/w_scr_dish_main_view_800x600.h \
    $$PWD/w_scr_dish_main_table_800x600.h \
    $$PWD/w_scr_dish_main.h \
    $$PWD/w_scr_dish_pay_widget.h \
    $$PWD/w_scr_dish_main_table_pay.h \
    $$PWD/w_scr_dish_pay_dialog.h \
    $$PWD/w_scr_dish_main_pay_info.h \
    $$PWD/w_scr_dish_main_bar_cancel.h \
    $$PWD/w_scr_dish_main_bar_cancel_win.h \
    $$PWD/w_scr_dish_restaurant_dishinfo.h \
    $$PWD/w_scr_dish_phone_pay.h \
    $$PWD/w_scr_dish_pay_set_ogg.h \
    $$PWD/w_scr_dish_main_qr_code.h \
    $$PWD/w_scr_dish_main_qr_code_over_view.h \
    $$PWD/w_scr_dish_main_qr_code_orderdish.h \
    $$PWD/w_scr_dish_main_qr_code_over_view_set.h \
    $$PWD/w_scr_dish_pay_kitchen_quit_request.h \
    $$PWD/w_scr_dish_main_view_scale.h \
    $$PWD/w_scr_dish_main_qr_code_over_view_cash_pay.h \
    $$PWD/w_scr_dish_main_separate.h \
    $$PWD/w_scr_dish_main_select_return.h \
    $$PWD/w_scr_dish_main_quit.h \
    $$PWD/business_data_upload_restful.h \
    $$PWD/business_interface_malayisa_hourly_pos.h \
    $$PWD/w_scr_dish_pay_widget_service_manual.h

SOURCES += \
    $$PWD/power_oper.cpp \
    $$PWD/takeout_cook.cpp \
    $$PWD/take_cashier.cpp \
    $$PWD/sqlquerymodel_linenum1.cpp \
    $$PWD/take_weight.cpp \
    $$PWD/bank_card.cpp \
    $$PWD/free_view.cpp \
    $$PWD/other_pay_view.cpp \
    $$PWD/waimai_pay.cpp \
    $$PWD/modify_password.cpp \
    $$PWD/lock_screen.cpp \
    $$PWD/business_documents_query.cpp \
    $$PWD/fast_qudan.cpp \
    $$PWD/bianma_cook.cpp \
    $$PWD/back_anti_checkout.cpp \
    $$PWD/w_scr_dish.cpp \
    $$PWD/w_scr_dish_data_collection.cpp \
    $$PWD/w_scr_dish_switch_detail.cpp \
    $$PWD/w_scr_balance_service.cpp \
    $$PWD/table_lock.cpp \
    $$PWD/linshi_cook.cpp \
    $$PWD/w_scr_dish_restaurant_dialog.cpp \
    $$PWD/w_scr_dish_cuicai_choose.cpp \
    $$PWD/w_scr_dish_cuicaipiece_choose.cpp \
    $$PWD/fast_pay_detail_dialog.cpp \
    $$PWD/w_scr_dish_m_hang_dialog.cpp \
    $$PWD/w_scr_dish_m_hang_pay_dialog.cpp \
    $$PWD/w_scr_dish_preorder_dialog.cpp \
    $$PWD/w_scr_dish_barscale.cpp \
    $$PWD/w_scr_dish_dish_change.cpp \
    $$PWD/w_scr_dish_restaurant_preorder.cpp \
    $$PWD/w_scr_dish_select_operid.cpp \
    $$PWD/system_setting_mobile_max_connect.cpp \
    $$PWD/w_scr_dish_restaurant_div_pop.cpp \
    $$PWD/w_scr_dish_restaurant_table_copy.cpp \
    $$PWD/w_scr_dish_restaurant_table_cmb.cpp \
    $$PWD/w_scr_dish_restaurant_table_transfer.cpp \
    $$PWD/w_scr_dish_num_cook_dialog.cpp \
    $$PWD/w_scr_dish_dish_quit.cpp \
    $$PWD/w_scr_dish_member.cpp \
    $$PWD/w_scr_dish_restaurant_table_dish_transfer.cpp \
    $$PWD/w_scr_dish_restaurant_table_select.cpp \
    $$PWD/w_scr_dish_pay_set.cpp \
    $$PWD/table_management_desk.cpp \
    $$PWD/table_management_graphicsview.cpp \
    $$PWD/table_management_pad.cpp \
    $$PWD/w_scr_dish_restaurant_paysomedish.cpp \
    $$PWD/w_scr_dish_restaurant_parameter.cpp \
    $$PWD/business_data_upload_isoft.cpp \
    $$PWD/w_scr_dish_group_dialog.cpp \
    $$PWD/w_scr_dish_pay_module_select.cpp \
    $$PWD/w_scr_dish_cook.cpp \
    $$PWD/w_scr_dish_guqing_report.cpp \
    $$PWD/w_scr_dish_language_switch_set.cpp \
    $$PWD/w_scr_dish_pay_select_language.cpp \
    $$PWD/w_scr_dish_main_view_800x600.cpp \
    $$PWD/w_scr_dish_main_table_800x600.cpp \
    $$PWD/w_scr_dish_main.cpp \
    $$PWD/w_scr_dish_pay_widget.cpp \
    $$PWD/w_scr_dish_main_table_pay.cpp \
    $$PWD/w_scr_dish_pay_dialog.cpp \
    $$PWD/w_scr_dish_main_pay_info.cpp \
    $$PWD/w_scr_dish_main_bar_cancel.cpp \
    $$PWD/w_scr_dish_main_bar_cancel_win.cpp \
    $$PWD/w_scr_dish_restaurant_dishinfo.cpp \
    $$PWD/w_scr_dish_phone_pay.cpp \
    $$PWD/w_scr_dish_pay_set_ogg.cpp \
    $$PWD/w_scr_dish_main_qr_code.cpp \
    $$PWD/w_scr_dish_main_qr_code_over_view.cpp \
    $$PWD/w_scr_dish_main_qr_code_orderdish.cpp \
    $$PWD/w_scr_dish_main_qr_code_over_view_set.cpp \
    $$PWD/w_scr_dish_pay_kitchen_quit_request.cpp \
    $$PWD/w_scr_dish_main_view_scale.cpp \
    $$PWD/w_scr_dish_main_qr_code_over_view_cash_pay.cpp \
    $$PWD/w_scr_dish_main_separate.cpp \
    $$PWD/w_scr_dish_main_select_return.cpp \
    $$PWD/w_scr_dish_main_quit.cpp \
    $$PWD/business_data_upload_restful.cpp \
    $$PWD/business_interface_malayisa_hourly_pos.cpp \
    $$PWD/w_scr_dish_pay_widget_service_manual.cpp

FORMS += \
    $$PWD/power_oper.ui \
    $$PWD/takeout_cook.ui \
    $$PWD/take_cashier.ui \
    $$PWD/take_weight.ui \
    $$PWD/bank_card.ui \
    $$PWD/free_view.ui \
    $$PWD/other_pay_view.ui \
    $$PWD/waimai_pay.ui \
    $$PWD/modify_password.ui \
    $$PWD/lock_screen.ui \
    $$PWD/business_documents_query.ui \
    $$PWD/fast_qudan.ui \
    $$PWD/bianma_cook.ui \
    $$PWD/back_anti_checkout.ui \
    $$PWD/w_scr_dish_special_cook.ui \
    $$PWD/w_scr_dish_data_collection_dialog.ui \
    $$PWD/w_scr_dish_switch_detail.ui\
    $$PWD/w_scr_balance_service.ui \
    $$PWD/table_lock.ui \
    $$PWD/linshi_cook.ui \
    $$PWD/w_scr_dish_restaurant_dialog.ui \
    $$PWD/fast_pay_detail_dialog.ui \
    $$PWD/w_scr_dish_m_hang_dialog.ui \
    $$PWD/w_scr_dish_m_hang_pay_dialog.ui \
    $$PWD/w_scr_dish_preorder_dialog.ui \
    $$PWD/w_scr_dish_dish_change.ui \
    $$PWD/w_scr_dish_restaurant_preorder.ui \
    $$PWD/w_scr_dish_restaurant_preorder_add_dialog.ui \
    $$PWD/w_scr_dish_restaurant_preorder_set.ui \
    $$PWD/system_setting_mobile_max_connect.ui \
    $$PWD/w_scr_dish_restaurant_div_pop.ui \
    $$PWD/w_scr_dish_restaurant_table_copy.ui \
    $$PWD/w_scr_dish_restaurant_table_cmb.ui \
    $$PWD/w_scr_dish_restaurant_table_transfer.ui \
    $$PWD/w_scr_dish_num_cook_dialog.ui \
    $$PWD/w_scr_dish_dish_quit.ui \
    $$PWD/w_scr_dish_member.ui \
    $$PWD/w_scr_dish_group_dialog.ui \
    $$PWD/w_scr_dish_restaurant_table_dish_transfer.ui \
    $$PWD/w_scr_dish_restaurant_table_select.ui \
    $$PWD/w_scr_dish_restaurant_parameter.ui \
    $$PWD/w_scr_dish_pay_module_select.ui \
    $$PWD/w_scr_dish_cook.ui \
    $$PWD/w_scr_dish_guqing_report.ui \
    $$PWD/w_scr_dish_language_switch_set.ui \
    $$PWD/w_scr_dish_pay_select_language.ui \
    $$PWD/w_scr_dish_main_view_800x600.ui \
    $$PWD/w_scr_dish_main_table_800x600.ui \
    $$PWD/w_scr_dish_pay_widget.ui \
    $$PWD/w_scr_dish_main_table_pay.ui \
    $$PWD/w_scr_dish_pay_dialog.ui \
    $$PWD/w_scr_dish_main_bar_cancel.ui \
    $$PWD/w_scr_dish_main_bar_cancel_win.ui \
    $$PWD/w_scr_dish_restaurant_dishinfo.ui \
    $$PWD/w_scr_dish_phone_pay.ui \
    $$PWD/w_scr_dish_pay_set_ogg.ui \
    $$PWD/w_scr_dish_main_qr_code_over_view.ui \
    $$PWD/w_scr_dish_main_qr_code_orderdish.ui \
    $$PWD/w_scr_dish_main_qr_code_over_view_set.ui \
    $$PWD/w_scr_dish_pay_kitchen_quit_request.ui \
    $$PWD/w_scr_dish_main_view_scale.ui \
    $$PWD/w_scr_dish_main_qr_code_over_view_cash_pay.ui \
    $$PWD/w_scr_dish_main_separate.ui \
    $$PWD/w_scr_dish_main_select_return.ui \
    $$PWD/w_scr_dish_main_quit.ui \
    $$PWD/business_data_upload_restful.ui \
    $$PWD/business_interface_malayisa_hourly_pos.ui \
    $$PWD/w_scr_dish_pay_widget_service_manual.ui
